services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network

  backend:
    container_name: nest-backend
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/kataalten?authSource=admin
      JWT_SECRET: secretkey
      NODE_ENV: development
    depends_on:
      - mongo
    networks:
      - backend-network
    command: sh -c "npm install && npm run start:dev"

networks:
  backend-network:
    driver: bridge

volumes:
  mongo_data:
